fpocket: cluster.c File Reference
cluster.c File Reference
#include "../headers/cluster.h"
Functions
void pck_ml_clust (c_lst_pockets *pockets, s_fparams *params)
void pck_ml_clust_test (c_lst_pockets *pockets, s_fparams *params)
Function Documentation
void pck_ml_clust (c_lst_pockets * pockets, s_fparams * params)
## FONCTION: void pck_ml_clust(c_lst_pockets *pockets, s_fparams *params)
## SPECIFICATION: This function will apply a mutliple linkage clustering algorithm on the given list of pockets. Considering two pockets, if params->ml_clust_min_nneigh alpha spheres are separated by a distance lower than params->ml_clust_max_dist, then merge the two pockets.
## PARAMETRES: @ c_lst_pockets *pockets : The list of pockets @ s_fparams *params : Parameters of the program, including single linkage parameters
## RETURN: void
Definition at line 89 of file cluster.c.
References dist(), c_lst_vertices::first, c_lst_pockets::first, mergePockets(), node_vertice::next, node_pocket::next, node_pocket::pocket, s_fparams::sl_clust_max_dist, s_fparams::sl_clust_min_nneigh, s_pocket::v_lst, node_vertice::vertice, s_vvertice::x, s_vvertice::y, and s_vvertice::z.
Referenced by search_pocket().
{
        node_pocket *pcur = NULL,
                                *pnext = NULL ,
                                *curMobilePocket = NULL ;
        node_vertice *vcur = NULL ;
        node_vertice *curMobileVertice = NULL ;
        s_vvertice *vvcur = NULL,
                           *mvvcur = NULL ;
        float vcurx,
                  vcury,
                  vcurz ;
        /* Flag to know if two clusters are next to each other by single linkage
         * clustering...or not */
        int nflag ;
        if(!pockets) {
                fprintf(stderr, "! Incorrect argument during Single Linkage Clustering.\n") ;
                return ;
        }
        /* Set the first pocket */
        pcur = pockets->first ;
        while(pcur) {
                /* Set the second pocket */
                curMobilePocket = pcur->next ;
                while(curMobilePocket) {
                        nflag = 0 ;
                        /* Set the first vertice/alpha sphere center of the first pocket */
                        vcur = pcur->pocket->v_lst->first ;
                        while(vcur && nflag <= params->sl_clust_min_nneigh){
                                /* Set the first vertice/alpha sphere center of the second pocket */
                                curMobileVertice = curMobilePocket->pocket->v_lst->first ;
                                vvcur = vcur->vertice ;
                                vcurx = vvcur->x ;
                                vcury = vvcur->y ;
                                vcurz = vvcur->z ;
                                /* Double loop for vertices -> if not near */
                                while(curMobileVertice && nflag <= params->sl_clust_min_nneigh){
                                        mvvcur = curMobileVertice->vertice ;
                                        if(dist(vcurx, vcury, vcurz, mvvcur->x, mvvcur->y, mvvcur->z)
                                                < params->sl_clust_max_dist) {
                                                                                                        /*if beneath the clustering max distance, increment the distance flag*/
                                                nflag++;
                                        }
                                        curMobileVertice = curMobileVertice->next;
                                }
                                vcur = vcur->next ;
                        }
                        pnext =  curMobilePocket->next ;
                        /* If the distance flag has counted enough occurences of near neighbours, merge pockets*/
                        if(nflag >= params->sl_clust_min_nneigh) {
                                /* If they are next to each other, merge them */
                                mergePockets(pcur,curMobilePocket,pockets);
                        }
                        curMobilePocket = pnext ;
                }
                pcur = pcur->next ;
        }
}
void pck_ml_clust_test (c_lst_pockets * pockets, s_fparams * params)
## FONCTION: void pck_ml_clust(c_lst_pockets *pockets, s_fparams *params)
## SPECIFICATION: This function will apply a mutliple linkage clustering algorithm on the given list of pockets. Considering two pockets, if params->ml_clust_min_nneigh alpha spheres are separated by a distance lower than params->ml_clust_max_dist, then merge the two pockets.
## PARAMETRES: @ c_lst_pockets *pockets : The list of pockets @ s_fparams *params : Parameters of the program, including single linkage parameters
## RETURN: void
Definition at line 175 of file cluster.c.
References dist(), c_lst_vertices::first, c_lst_pockets::first, mergePockets(), node_vertice::next, node_pocket::next, node_pocket::pocket, s_fparams::sl_clust_max_dist, s_fparams::sl_clust_min_nneigh, s_pocket::v_lst, node_vertice::vertice, s_vvertice::x, s_vvertice::y, and s_vvertice::z.
{
        node_pocket *pcur = NULL,
                                *pnext = NULL ,
                                *curMobilePocket = NULL ;
        node_vertice *vcur = NULL ;
        node_vertice *curMobileVertice = NULL ;
        s_vvertice *vvcur = NULL,
                           *mvvcur = NULL ;
        float vcurx,
                  vcury,
                  vcurz ;
        /* Flag to know if two clusters are next to each other by single linkage
         * clustering...or not */
        int nflag,
                restart = 0;
        if(!pockets) {
                fprintf(stderr, "! Incorrect argument during Single Linkage Clustering.\n") ;
                return ;
        }
        printf("ML starting\n") ;
        /* Set the first pocket */
        pcur = pockets->first ;
        while(pcur) {
                /* Set the second pocket */
                curMobilePocket = pcur->next ;
                while(curMobilePocket) {
                        nflag = 0 ;
                        /* Set the first vertice/alpha sphere center of the first pocket */
                        vcur = pcur->pocket->v_lst->first ;
                        while(vcur && nflag <= params->sl_clust_min_nneigh){
                                /* Set the first vertice/alpha sphere center of the second pocket */
                                curMobileVertice = curMobilePocket->pocket->v_lst->first ;
                                vvcur = vcur->vertice ;
                                vcurx = vvcur->x ;
                                vcury = vvcur->y ;
                                vcurz = vvcur->z ;
                                /* Double loop for vertices -> if not near */
                                while(curMobileVertice && nflag <= params->sl_clust_min_nneigh){
                                        mvvcur = curMobileVertice->vertice ;
                                        if(dist(vcurx, vcury, vcurz, mvvcur->x, mvvcur->y, mvvcur->z)
                                                < params->sl_clust_max_dist) {
                                                                                                        /*if beneath the clustering max distance, increment the distance flag*/
                                                nflag++;
                                                break ; /* Ensure that at least N vertice in one of the
                                                                   two pockets have N vertice at a distance
                                                                   <= SL_MAX_DST */
                                        }
                                        curMobileVertice = curMobileVertice->next;
                                }
                                vcur = vcur->next ;
                        }
                        pnext =  curMobilePocket->next ;
                        /* If the distance flag has counted enough occurences of near neighbours, merge pockets*/
                        if(nflag >= params->sl_clust_min_nneigh) {
                                /* If they are next to each other, merge them */
                                mergePockets(pcur,curMobilePocket,pockets);
                                restart = 1 ; printf("Merging\n") ;
                                break ;
                        }
                        curMobilePocket = pnext ;
                }
                /* Restart the algorithm if two pockets have been merged */
                if(restart == 1) {
                        restart = 0 ;
                        pcur = pockets->first ;
                }
                else pcur = pcur->next ;
        }
        printf("ML ending\n") ;
}