fpocket: fparams.h File Reference
fparams.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <ctype.h>
#include <limits.h>
#include <assert.h>
#include "utils.h"
#include "memhandler.h"
Data Structures
struct s_fparams
Defines
#define M_MIN_ASHAPE_SIZE_DEFAULT 3.0
#define M_MAX_ASHAPE_SIZE_DEFAULT 6.0
#define M_CLUST_MAX_DIST 1.73
#define M_REFINE_DIST 4.5
#define M_REFINE_MIN_PROP_APOL_AS 0.0
#define M_SLCLUST_MAX_DIST 2.5
#define M_SLCLUST_MIN_NUM_NEIGH 2
#define M_MC_ITER 3000
#define M_BASIC_VOL_DIVISION -1
#define M_MIN_POCK_NB_ASPH 36
#define M__MIN_APOL_NEIGH_DEFAULT 3
#define M_PAR_PDB_FILE 'f'
#define M_PAR_PDB_LIST 'F'
#define M_PAR_MAX_ASHAPE_SIZE 'M'
#define M_PAR_MIN_ASHAPE_SIZE 'm'
#define M_PAR_MIN_APOL_NEIGH 'A'
#define M_PAR_CLUST_MAX_DIST 'D'
#define M_PAR_SL_MAX_DIST 's'
#define M_PAR_SL_MIN_NUM_NEIGH 'n'
#define M_PAR_MC_ITER 'v'
#define M_PAR_BASIC_VOL_DIVISION 'b'
#define M_PAR_MIN_POCK_NB_ASPH 'i'
#define M_PAR_REFINE_DIST 'r'
#define M_PAR_REFINE_MIN_NAPOL_AS 'p'
#define M_FP_USAGE "\n\***** USAGE (fpocket) *****\n\\n\Pocket finding on a pdb - list of pdb - file(s): \n\\t./bin/fpocket -f pdb \n\\t./bin/fpocket -F pdb_list \n\\nOPTIONS (find standard parameters in brackets) \n\n\\t-m (float) : Minimum radius of an alpha-sphere. (3.0)\n\\t-M (float) : Maximum radius of an alpha-sphere. (6.0)\n\\t-A (int) : Minimum number of apolar neighbor for \n\\t an a-sphere to be considered as apolar. (3)\n\\t-i (int) : Minimum number of a-sphere per pocket. (30)\n\\t-D (float) : Maximum distance for first clustering \n\\t algorithm. (1.73)\n\\t-s (float) : Maximum distance for single linkage \n\\t clustering (2.5)\n\\t-n (integer): Minimum number of neighbor close from \n\\t each other (not merged otherwise). (3)\n\\t-r (float) : Maximum distance between two pockets \n\\t barycenter (merged otherwise). (4.5)\n\\t-p (float) : Minimum proportion of apolar sphere in \n\\t a pocket (remove otherwise) (0.0)\n\\t-v (integer): Number of Monte-Carlo iteration for the \n\\t calculation of each pocket volume. (2500)\n\\t-b (integer): Space approximation for the basic method \n\\t of the volume calculation. Not used by \n\\t default (Monte Carlo approximation is) \n\\nSee the manual (man fpocket), or the full documentation for\n\more information.\n\***************************\n"
Functions
s_fparams * init_def_fparams (void)
s_fparams * get_fpocket_args (int nargs, char **args)
int parse_clust_max_dist (char *str, s_fparams *p)
int parse_sclust_max_dist (char *str, s_fparams *p)
int parse_sclust_min_nneigh (char *str, s_fparams *p)
int parse_min_apol_neigh (char *str, s_fparams *p)
int parse_asph_min_size (char *str, s_fparams *p)
int parse_asph_max_size (char *str, s_fparams *p)
int parse_mc_niter (char *str, s_fparams *p)
int parse_basic_vol_div (char *str, s_fparams *p)
int parse_refine_dist (char *str, s_fparams *p)
int parse_refine_minaap (char *str, s_fparams *p)
int parse_min_pock_nb_asph (char *str, s_fparams *p)
int is_fpocket_opt (const char opt)
void free_fparams (s_fparams *p)
void print_pocket_usage (FILE *f)
void print_fparams (s_fparams *p, FILE *f)
Define Documentation
#define M__MIN_APOL_NEIGH_DEFAULT 3
Minimum number of atoms having a low electronegativity in order to declare an alpha sphere to be apolar 3
Definition at line 76 of file fparams.h.
Referenced by init_def_fparams().
#define M_BASIC_VOL_DIVISION -1
Precision for "exact" volume integration, set to -1 if not used -1
Definition at line 72 of file fparams.h.
Referenced by init_def_fparams().
#define M_CLUST_MAX_DIST 1.73
Use first connection distance (see report) : 2.0
Definition at line 60 of file fparams.h.
Referenced by init_def_fparams().
#define M_FP_USAGE "\n\***** USAGE (fpocket) *****\n\\n\Pocket finding on a pdb - list of pdb - file(s): \n\\t./bin/fpocket -f pdb \n\\t./bin/fpocket -F pdb_list \n\\nOPTIONS (find standard parameters in brackets) \n\n\\t-m (float) : Minimum radius of an alpha-sphere. (3.0)\n\\t-M (float) : Maximum radius of an alpha-sphere. (6.0)\n\\t-A (int) : Minimum number of apolar neighbor for \n\\t an a-sphere to be considered as apolar. (3)\n\\t-i (int) : Minimum number of a-sphere per pocket. (30)\n\\t-D (float) : Maximum distance for first clustering \n\\t algorithm. (1.73)\n\\t-s (float) : Maximum distance for single linkage \n\\t clustering (2.5)\n\\t-n (integer): Minimum number of neighbor close from \n\\t each other (not merged otherwise). (3)\n\\t-r (float) : Maximum distance between two pockets \n\\t barycenter (merged otherwise). (4.5)\n\\t-p (float) : Minimum proportion of apolar sphere in \n\\t a pocket (remove otherwise) (0.0)\n\\t-v (integer): Number of Monte-Carlo iteration for the \n\\t calculation of each pocket volume. (2500)\n\\t-b (integer): Space approximation for the basic method \n\\t of the volume calculation. Not used by \n\\t default (Monte Carlo approximation is) \n\\nSee the manual (man fpocket), or the full documentation for\n\more information.\n\***************************\n"
the usage print content
Definition at line 94 of file fparams.h.
Referenced by print_pocket_usage().
#define M_MAX_ASHAPE_SIZE_DEFAULT 6.0
Use max alpha sphere radius of : 6.0
Definition at line 58 of file fparams.h.
Referenced by init_def_fparams().
#define M_MC_ITER 3000
Number of iterations for the Monte Carlo volume calculation 3000
Definition at line 70 of file fparams.h.
Referenced by init_def_fparams().
#define M_MIN_ASHAPE_SIZE_DEFAULT 3.0
Use min alpha sphere radius of : 3.0
Definition at line 56 of file fparams.h.
Referenced by init_def_fparams().
#define M_MIN_POCK_NB_ASPH 36
Minimum number of alpha spheres for a pocket to be kept
Definition at line 74 of file fparams.h.
Referenced by init_def_fparams().
#define M_PAR_BASIC_VOL_DIVISION 'b'
flag for the space approximation of the MC
Definition at line 89 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_CLUST_MAX_DIST 'D'
flag for the first clustering distance
Definition at line 85 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_MAX_ASHAPE_SIZE 'M'
flag for the maximum alpha sphere size
Definition at line 82 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_MC_ITER 'v'
flag for how many iterations for the monte carlo volume calculation algorithm
Definition at line 88 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_MIN_APOL_NEIGH 'A'
flag for the minimum number of apolar neighbours for an alpha sphere to be considered as apolar
Definition at line 84 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_MIN_ASHAPE_SIZE 'm'
flag for the minimum alpha sphere size
Definition at line 83 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_MIN_POCK_NB_ASPH 'i'
flag for the min number of alpha spheres in the pocket
Definition at line 90 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_PDB_FILE 'f'
flag to give a single pdb input file
Definition at line 80 of file fparams.h.
Referenced by get_fpocket_args().
#define M_PAR_PDB_LIST 'F'
flag to give a txt file containing paths to multiple pdb files
Definition at line 81 of file fparams.h.
Referenced by get_fpocket_args().
#define M_PAR_REFINE_DIST 'r'
flag for the refining distance
Definition at line 91 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_REFINE_MIN_NAPOL_AS 'p'
flag for minimum proportion of apolar alpha spheres
Definition at line 92 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_SL_MAX_DIST 's'
flag for the distance crit. of the multiple linkage clustering algorithm
Definition at line 86 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_PAR_SL_MIN_NUM_NEIGH 'n'
flag for the single linkage min neighbours
Definition at line 87 of file fparams.h.
Referenced by get_fpocket_args(), and is_fpocket_opt().
#define M_REFINE_DIST 4.5
use second connection distance (see report) : 4.5
Definition at line 62 of file fparams.h.
Referenced by init_def_fparams().
#define M_REFINE_MIN_PROP_APOL_AS 0.0
At least a proportion of M_REFINE_MIN_NAPOL_AS apolar alpha spheres in the pocket 0.0
Definition at line 64 of file fparams.h.
Referenced by init_def_fparams().
#define M_SLCLUST_MAX_DIST 2.5
Single linkage clustering connection distance 2.5
Definition at line 66 of file fparams.h.
Referenced by init_def_fparams().
#define M_SLCLUST_MIN_NUM_NEIGH 2
Minimum number of common neighbours for single linkage clustering 5
Definition at line 68 of file fparams.h.
Referenced by init_def_fparams().
Function Documentation
void free_fparams (s_fparams * p)
## FUNCTION: free_fparams
## SPECIFICATION: Free parameters
## PARAMETRES: @ s_params *p: Pointer to the structure to free
## RETURN: void
Definition at line 553 of file fparams.c.
References my_free(), s_fparams::npdb, and s_fparams::pdb_lst.
Referenced by check_fpocket(), free_dparams(), free_tparams(), get_fpocket_args(), and main().
{
        if(p) {
                if(p->npdb > 0 && p->pdb_lst != NULL) {
                        int i ;
                        for (i = 0 ; i < p->npdb ; i++) {
                                if(p->pdb_lst[i] != NULL) my_free(p->pdb_lst[i]) ;
                        }
                        my_free(p->pdb_lst) ;
                }
                my_free(p) ;
        }
}
s_fparams* get_fpocket_args (int nargs, char ** args)
## FUNCTION: get_fpocket_args
## SPECIFICATION: This function analyse the user's command line and parse it to store parameters for the pocket finder programm.
## PARAMETRES: @ int nargs : Number of arguments @ char **args : Arguments of main program
## RETURN: s_params*: Pointer to parameters
Definition at line 86 of file fparams.c.
References free_fparams(), init_def_fparams(), M_MAX_PDB_NAME_LEN, M_PAR_BASIC_VOL_DIVISION, M_PAR_CLUST_MAX_DIST, M_PAR_MAX_ASHAPE_SIZE, M_PAR_MC_ITER, M_PAR_MIN_APOL_NEIGH, M_PAR_MIN_ASHAPE_SIZE, M_PAR_MIN_POCK_NB_ASPH, M_PAR_PDB_FILE, M_PAR_PDB_LIST, M_PAR_REFINE_DIST, M_PAR_REFINE_MIN_NAPOL_AS, M_PAR_SL_MAX_DIST, M_PAR_SL_MIN_NUM_NEIGH, my_malloc(), s_fparams::npdb, parse_asph_max_size(), parse_asph_min_size(), parse_basic_vol_div(), parse_clust_max_dist(), parse_mc_niter(), parse_min_apol_neigh(), parse_min_pock_nb_asph(), parse_refine_dist(), parse_refine_minaap(), parse_sclust_max_dist(), parse_sclust_min_nneigh(), s_fparams::pdb_lst, s_fparams::pdb_path, and print_pocket_usage().
Referenced by check_fparams(), check_fpocket(), get_dpocket_args(), get_tpocket_args(), and main().
{
        int i,
                npdb = 0,
                status = 0 ;
        s_fparams *par = init_def_fparams() ;
        char *pdb_lst = NULL ;
        //read arguments by flags
        for (i = 1; i < nargs; i++) {
                if (strlen(args[i]) == 2 && args[i][0] == '-' && i < (nargs-1)) {
                        switch (args[i][1]) {
                                case M_PAR_MAX_ASHAPE_SIZE        :
                                        status += parse_asph_max_size(args[++i], par) ;         break ;
                                case M_PAR_MIN_ASHAPE_SIZE        :
                                        status += parse_asph_min_size(args[++i], par) ;         break ;
                                case M_PAR_MIN_APOL_NEIGH         :
                                        status += parse_min_apol_neigh(args[++i], par) ;        break ;
                                case M_PAR_CLUST_MAX_DIST         :
                                        status += parse_clust_max_dist(args[++i], par) ;        break ;
                                case M_PAR_SL_MAX_DIST            :
                                        status += parse_sclust_max_dist(args[++i], par) ;       break ;
                                case M_PAR_SL_MIN_NUM_NEIGH   :
                                        status += parse_sclust_min_nneigh(args[++i], par) ; break ;
                                case M_PAR_MC_ITER                        :
                                        status += parse_mc_niter(args[++i], par) ;                      break ;
                                case M_PAR_BASIC_VOL_DIVISION :
                                        status += parse_basic_vol_div(args[++i], par) ;         break ;
                                case M_PAR_MIN_POCK_NB_ASPH   :
                                        status += parse_min_pock_nb_asph(args[++i], par) ;      break ;
                                case M_PAR_REFINE_DIST            :
                                        status += parse_refine_dist(args[++i], par) ;           break ;
                                case M_PAR_REFINE_MIN_NAPOL_AS:
                                        status += parse_refine_minaap(args[++i], par) ;
                                        break ;
                                case M_PAR_PDB_LIST :
                                        pdb_lst = args[++i] ; break ;
                                case M_PAR_PDB_FILE                       :
                                                if(npdb >= 1) fprintf(stderr,
                                                        "! Only first input pdb will be used.\n") ;
                                                else {
                                                        strcpy(par->pdb_path, args[++i]) ; npdb++ ;
                                                }
                                                break ;
                                default: break ;
                        }
                }
        }
        if(status > 0) {
                free_fparams(par) ;
                print_pocket_usage(stdout);
                return NULL ;
        }
        par->npdb = npdb ;
        /* Handle a file containing a list of PDB */
        if(pdb_lst != NULL) {
                FILE *f = fopen(pdb_lst, "r") ;
                if(f != NULL) {
                        /* Count the number of lines */
                        int n = 0 ;
                        char cline [M_MAX_PDB_NAME_LEN + 1] ;
                        while(fgets(cline, M_MAX_PDB_NAME_LEN, f) != NULL) {
                                if(strcmp("\n", cline) != 0) {
                                        n ++ ;
                                }
                        }
                        fclose(f) ;
                        if(n == 0) {
                                return par ;
                        }
                        /* Allocate memory and store each line */
                        par->pdb_lst = (char **)my_malloc(n*sizeof(char*)) ;
                        f = fopen (pdb_lst, "r") ;
                        int i = 0, l = 0 ;
                        while(fgets(cline, M_MAX_PDB_NAME_LEN, f) != NULL) {
                                if(strcmp("\n", cline) != 0) {
                                        l = strlen(cline) ;
                                        if(cline[l-1] == '\n') {
                                                l ;
                                                cline[l] = '\0' ;
                                        }
                                        char *line = (char *) my_malloc((l+1)*sizeof(char)) ;
                                        memcpy (line, cline, l+1);
                                        par->pdb_lst[i] = line ;
                                        i ++ ;
                                }
                        }
                        par->npdb = n ;
                }
        }
        return par;
}
s_fparams* init_def_fparams (void)
## FUNCTION: init_def_fparams
## SPECIFICATION: Initialisation of default parameters
## PARAMETRES: void
## RETURN: s_fparams*: Pointer to allocated paramers.
Definition at line 48 of file fparams.c.
References s_fparams::asph_max_size, s_fparams::asph_min_size, s_fparams::basic_volume_div, s_fparams::clust_max_dist, M__MIN_APOL_NEIGH_DEFAULT, M_BASIC_VOL_DIVISION, M_CLUST_MAX_DIST, M_MAX_ASHAPE_SIZE_DEFAULT, M_MC_ITER, M_MIN_ASHAPE_SIZE_DEFAULT, M_MIN_POCK_NB_ASPH, M_REFINE_DIST, M_REFINE_MIN_PROP_APOL_AS, M_SLCLUST_MAX_DIST, M_SLCLUST_MIN_NUM_NEIGH, s_fparams::min_apol_neigh, s_fparams::min_pock_nb_asph, my_malloc(), s_fparams::nb_mcv_iter, s_fparams::npdb, s_fparams::pdb_lst, s_fparams::pdb_path, s_fparams::refine_clust_dist, s_fparams::refine_min_apolar_asphere_prop, s_fparams::sl_clust_max_dist, and s_fparams::sl_clust_min_nneigh.
Referenced by get_fpocket_args().
{
        s_fparams *par = (s_fparams *) my_malloc(sizeof(s_fparams)) ;
        par->min_apol_neigh = M__MIN_APOL_NEIGH_DEFAULT ;
        par->asph_min_size = M_MIN_ASHAPE_SIZE_DEFAULT ;
        par->asph_max_size = M_MAX_ASHAPE_SIZE_DEFAULT ;
        par->sl_clust_max_dist = M_SLCLUST_MAX_DIST ;
        par->sl_clust_min_nneigh = M_SLCLUST_MIN_NUM_NEIGH ;
        par->pdb_path[0] = 0 ;
        par->basic_volume_div = M_BASIC_VOL_DIVISION ;
        par->nb_mcv_iter = M_MC_ITER ;
        par->min_pock_nb_asph = M_MIN_POCK_NB_ASPH ;
        par->refine_clust_dist = M_REFINE_DIST ;
        par->refine_min_apolar_asphere_prop = M_REFINE_MIN_PROP_APOL_AS ;
        par->clust_max_dist = M_CLUST_MAX_DIST ;
        par->npdb = 0 ;
        par->pdb_lst = NULL ;
        return par ;
}
int is_fpocket_opt (const char opt)
## FUNCTION: is_fpocket_opt
## SPECIFICATION: Say either or not a single letter code is a fpocket option (excluding input file/list option.)
## PARAMETRES: @ const char opt: The one letter code option.
## RETURN: integer: 1 if it's a valid option parmeter, 0 if not.
Definition at line 520 of file fparams.c.
References M_PAR_BASIC_VOL_DIVISION, M_PAR_CLUST_MAX_DIST, M_PAR_MAX_ASHAPE_SIZE, M_PAR_MC_ITER, M_PAR_MIN_APOL_NEIGH, M_PAR_MIN_ASHAPE_SIZE, M_PAR_MIN_POCK_NB_ASPH, M_PAR_REFINE_DIST, M_PAR_REFINE_MIN_NAPOL_AS, M_PAR_SL_MAX_DIST, and M_PAR_SL_MIN_NUM_NEIGH.
Referenced by get_dpocket_args(), and get_tpocket_args().
{
        if( opt == M_PAR_MAX_ASHAPE_SIZE ||
                opt == M_PAR_MIN_ASHAPE_SIZE ||
                opt == M_PAR_MIN_APOL_NEIGH ||
                opt == M_PAR_CLUST_MAX_DIST ||
                opt == M_PAR_SL_MAX_DIST ||
                opt == M_PAR_SL_MIN_NUM_NEIGH ||
                opt == M_PAR_MC_ITER ||
                opt == M_PAR_BASIC_VOL_DIVISION ||
                opt == M_PAR_MIN_POCK_NB_ASPH ||
                opt == M_PAR_REFINE_DIST ||
                opt == M_PAR_REFINE_MIN_NAPOL_AS) {
                return 1 ;
        }
        return 0 ;
}
int parse_asph_max_size (char * str, s_fparams * p)
## FUNCTION: parse_asph_max_size
## SPECIFICATION: Parsing function for the maximum radius of each alpha shpere
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid float), 1 if not
Definition at line 349 of file fparams.c.
References s_fparams::asph_max_size, M_NO_SIGN, and str_is_float().
Referenced by get_fpocket_args().
{
        if(str_is_float(str, M_NO_SIGN)) {
                p->asph_max_size = (float) atof(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the max radius of alpha shperes.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_asph_min_size (char * str, s_fparams * p)
## FUNCTION: parse_asph_min_size
## SPECIFICATION: Parsing function for the minimum radius of each alpha shpere
## PARAMETERS: @ char *str: The string to parse @ s_fparams *p: The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid float), 1 if not
Definition at line 321 of file fparams.c.
References s_fparams::asph_min_size, M_NO_SIGN, and str_is_float().
Referenced by get_fpocket_args().
{
        if(str_is_float(str, M_NO_SIGN)) {
                p->asph_min_size = (float) atof(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the min radius of alpha shperes.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_basic_vol_div (char * str, s_fparams * p)
## FUNCTION: parse_basic_vol_div
## SPECIFICATION: Parsing function for the number of iteration for the basic volume calculation.
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid integer), 1 if not
Definition at line 406 of file fparams.c.
References s_fparams::basic_volume_div, M_NO_SIGN, and str_is_number().
Referenced by get_fpocket_args().
{
        if(str_is_number(str, M_NO_SIGN)) {
                p->basic_volume_div = (int) atoi(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the precision of the basic volume calculation.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_clust_max_dist (char * str, s_fparams * p)
## FUNCTION: parse_clust_max_dist
## SPECIFICATION: Parsing function for the distance criteria first clustering algorithm.
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid float), 1 if not
Definition at line 205 of file fparams.c.
References s_fparams::clust_max_dist, M_NO_SIGN, and str_is_float().
Referenced by get_fpocket_args().
{
        if(str_is_float(str, M_NO_SIGN)) {
                p->clust_max_dist = atof(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the single linkage max dist.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_mc_niter (char * str, s_fparams * p)
## FUNCTION: parse_mc_niter
## SPECIFICATION: Parsing function for the number of iteration for the Monte Carlo volume calculation.
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid float), 1 if not
Definition at line 378 of file fparams.c.
References M_NO_SIGN, s_fparams::nb_mcv_iter, and str_is_float().
Referenced by get_fpocket_args().
{
        if(str_is_float(str, M_NO_SIGN)) {
                p->nb_mcv_iter = (int) atoi(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the number of monte-carlo iteration for the volume.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_min_apol_neigh (char * str, s_fparams * p)
## FUNCTION: parse_min_apol_neigh
## SPECIFICATION: Parsing function for the minimum number of apolar contacted atom for an alpha sphere to be considered as apolar.
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid int), 1 if not
Definition at line 291 of file fparams.c.
References M_NO_SIGN, s_fparams::min_apol_neigh, and str_is_number().
Referenced by get_fpocket_args().
{
        if(str_is_number(str, M_NO_SIGN)) {
                p->min_apol_neigh = (int) atoi(str) ;
                if(p->min_apol_neigh < 0) p->min_apol_neigh = 0 ;
                if(p->min_apol_neigh > 4) p->min_apol_neigh = 4 ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the min radius of alpha shperes.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_min_pock_nb_asph (char * str, s_fparams * p)
## FUNCTION: parse_min_pock_nb_asph
## SPECIFICATION: Parsing function for the minimum number of alpha sphere per pocket.
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid integer), 1 if not
Definition at line 490 of file fparams.c.
References M_NO_SIGN, s_fparams::min_pock_nb_asph, and str_is_number().
Referenced by get_fpocket_args().
{
        if(str_is_number(str, M_NO_SIGN)) {
                p->min_pock_nb_asph = (int) atoi(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the refine distance.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_refine_dist (char * str, s_fparams * p)
## FUNCTION: parse_refine_dist
## SPECIFICATION: Parsing function for the distance in the refine algorithm
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid float), 1 if not
Definition at line 434 of file fparams.c.
References M_NO_SIGN, s_fparams::refine_clust_dist, and str_is_float().
Referenced by get_fpocket_args().
{
        if(str_is_float(str, M_NO_SIGN)) {
                p->refine_clust_dist = (float) atof(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the refine distance.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_refine_minaap (char * str, s_fparams * p)
## FUNCTION: parse_refine_min_apol
## SPECIFICATION: Parsing function for the minimum number of apolar sphere per pocket.
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid integer), 1 if not
Definition at line 462 of file fparams.c.
References M_NO_SIGN, s_fparams::refine_min_apolar_asphere_prop, and str_is_float().
Referenced by get_fpocket_args().
{
        if(str_is_float(str, M_NO_SIGN)) {
                p->refine_min_apolar_asphere_prop = (float) atof(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the refine distance.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_sclust_max_dist (char * str, s_fparams * p)
## FUNCTION: parse_sclust_max_dist
## SPECIFICATION: Parsing function for the distance criteria in the single linkage clustering.
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid float), 1 if not
Definition at line 234 of file fparams.c.
References M_NO_SIGN, s_fparams::sl_clust_max_dist, and str_is_float().
Referenced by get_fpocket_args().
{
        if(str_is_float(str, M_NO_SIGN)) {
                p->sl_clust_max_dist = atof(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the single linkage max dist.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
int parse_sclust_min_nneigh (char * str, s_fparams * p)
## FUNCTION: parse_sclust_min_nneigh
## SPECIFICATION: Parsing function for the number of neighbours in the single linkage clustering.
## PARAMETERS: @ char *str : The string to parse @ s_fparams *p : The structure than will contain the parsed parameter
## RETURN: int: 0 if the parameter is valid (here a valid int), 1 if not
Definition at line 262 of file fparams.c.
References M_NO_SIGN, s_fparams::sl_clust_min_nneigh, and str_is_number().
Referenced by get_fpocket_args().
{
        if(str_is_number(str, M_NO_SIGN)) {
                p->sl_clust_min_nneigh = atoi(str) ;
        }
        else {
                fprintf(stdout, "! Invalid value (%s) given for the single linkage max dist.\n", str) ;
                return 1 ;
        }
        return 0 ;
}
void print_fparams (s_fparams * p, FILE * f)
## FUNCTION: print_fparams
## SPECIFICATION: Print function
## PARAMETRES: @ s_fparams *p : Parameters to print @ FILE *f : Buffer to write in
## RETURN:
Definition at line 602 of file fparams.c.
References s_fparams::asph_max_size, s_fparams::asph_min_size, s_fparams::basic_volume_div, s_fparams::clust_max_dist, s_fparams::min_apol_neigh, s_fparams::nb_mcv_iter, s_fparams::pdb_path, s_fparams::refine_clust_dist, s_fparams::refine_min_apolar_asphere_prop, s_fparams::sl_clust_max_dist, and s_fparams::sl_clust_min_nneigh.
{
        if(p) {
                fprintf(f, "==============\nParameters of fpocket: \n");
                fprintf(f, "> Minimum alpha sphere radius: %f\n", p->asph_min_size);
                fprintf(f, "> Maximum alpha sphere radius: %f\n", p->asph_max_size);
                fprintf(f, "> Minimum number of apolar neighbor: %d\n", p->min_apol_neigh);
                fprintf(f, "> Maximum distance for first clustering algorithm: %f \n", p->clust_max_dist) ;
                fprintf(f, "> Single linkage clustering distance: %f\n", p->sl_clust_max_dist);
                fprintf(f, "> Single linkage clustering neighbor: %d\n", p->sl_clust_min_nneigh);
                fprintf(f, "> Refine clustering distance: %f\n", p->refine_clust_dist);
                fprintf(f, "> Min number of apolar sphere in refine to keep a pocket: %f\n", p->refine_min_apolar_asphere_prop) ;
                fprintf(f, "> Monte carlo iterations: %d\n", p->nb_mcv_iter);
                fprintf(f, "> Basic method for volume calculation: %d\n", p->basic_volume_div);
                fprintf(f, "> PDB file: %s\n", p->pdb_path);
                fprintf(f, "==============\n");
        }
        else fprintf(f, "> No parameters detected\n");
}
void print_pocket_usage (FILE * f)
## FUNCTION: print_pocket_usage
## SPECIFICATION: Displaying usage of the programm in the given buffer
## PARAMETRES: @ FILE *f: buffer to print in
## RETURN: void
Definition at line 581 of file fparams.c.
References M_FP_USAGE.
Referenced by get_fpocket_args(), and main().
{
        f = (f == NULL) ? stdout:f ;
        fprintf(f, M_FP_USAGE) ;
}