fpocket: fpout.c File Reference
fpout.c File Reference
#include "../headers/fpout.h"
Functions
void write_out_fpocket (c_lst_pockets *pockets, s_pdb *pdb, char *pdbname)
Function Documentation
void write_out_fpocket (c_lst_pockets * pockets, s_pdb * pdb, char * pdbname)
## FUNCTION: write_out_fpocket
## SPECIFICATION: Output routine. See the documentation for more information.
## PARAMETRES: @ c_lst_pockets *pockets : All pockets found and kept. @ c_lst_pockets *pockets : The (input) pdb structure @ char *pdbname : Name of the pdb
## RETURN: void
Definition at line 79 of file fpout.c.
References extract_path(), remove_ext(), remove_path(), write_each_pocket(), write_pockets_single_pdb(), write_pockets_single_pqr(), and write_visualization().
Referenced by check_fpocket(), process_pdb(), and test_set().
{
        char pdb_code[350] = "" ;
        char pdb_path[350] = "" ;
        char out_path[350] = "" ;
        char pdb_out_path[350] = "" ;
        char fout[350] = "" ;
        char command[370] = "" ;
        int status ;
        if(pockets) {
        /* Extract path, pdb code... */
                strcpy(pdb_code, pdbname) ;
                extract_path(pdbname, pdb_path) ;
                remove_ext(pdb_code) ;
                remove_path(pdb_code) ;
                if(strlen(pdb_path) > 0) sprintf(out_path, "%s/%s_out", pdb_path, pdb_code) ;
                else sprintf(out_path, "%s_out", pdb_code) ;
                sprintf(command, "mkdir %s", out_path) ;
                status = system(command) ;
                /*if(status != 0) {
                        return ;
                }*/
                sprintf(out_path, "%s/%s", out_path, pdb_code) ;
                sprintf(pdb_out_path, "%s_out.pdb", out_path) ;
        /* Write vmd and pymol scripts */
                sprintf(fout, "%s_out.pdb", pdb_code) ;
                write_visualization(out_path, fout);
        /* Writing full pdb */
                sprintf(pdb_out_path, "%s_out.pdb", out_path) ;
                write_pockets_single_pdb(pdb_out_path, pdb, pockets) ;
        /* Writing pockets as a single pqr */
                sprintf(fout, "%s_pockets.pqr", out_path) ;
                write_pockets_single_pqr(fout, pockets) ;
        /* Writing individual pockets pqr */
                if(strlen(pdb_path) > 0) sprintf(out_path, "%s/%s_out", pdb_path, pdb_code) ;
                else sprintf(out_path, "%s_out", pdb_code) ;
                sprintf(out_path, "%s/pockets", out_path) ;
                sprintf(command, "mkdir %s", out_path) ;
                status = system(command) ;
                if(status != 0) {
                        return ;
                }
                write_each_pocket(out_path, pockets) ;
        }
}