/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RasmolCommandPanel.java
 *
 * Created on Oct 14, 2009, 12:37:22 PM
 */

package jpocket.gui;

/**
 *
 * @author vince
 */
public class RasmolCommandPanel extends javax.swing.JPanel
{
    public static final String RASMOL_COM = "RCOM";

    /** Creates new form RasmolCommandPanel */
    public RasmolCommandPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        executeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rasmolCommandTA = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jSeparator1, java.awt.BorderLayout.PAGE_END);
        jPanel1.add(jSeparator2, java.awt.BorderLayout.PAGE_START);

        executeButton.setText("Execute");
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(executeButton, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        rasmolCommandTA.setColumns(20);
        rasmolCommandTA.setRows(5);
        jScrollPane1.setViewportView(rasmolCommandTA);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        if(rasmolCommandTA.getText() != null && ! "".equals(rasmolCommandTA.getText())) ;
            firePropertyChange(RASMOL_COM, null, rasmolCommandTA.getText()) ;
    }//GEN-LAST:event_executeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton executeButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea rasmolCommandTA;
    // End of variables declaration//GEN-END:variables

}
